substitutions:
  _SERVICE_NAME: nerius-frontend
  _REGION: us-central1
  _AR_REPOSITORY: cloud-run
  _BACKEND_URL: https://nerius-backend-862131549348.us-central1.run.app

steps:
  - name: gcr.io/cloud-builders/docker
    id: Build image
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_SERVICE_NAME}:latest
      - .

  - name: gcr.io/cloud-builders/docker
    id: Push commit image
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA

  - name: gcr.io/cloud-builders/docker
    id: Push latest image
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_SERVICE_NAME}:latest

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: Deploy to Cloud Run
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --set-env-vars
      - BACKEND_URL=${_BACKEND_URL}

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_SERVICE_NAME}:latest

options:
  logging: CLOUD_LOGGING_ONLY